language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
deploy:
  provider: surge
  script: npm run deploy
  skip_cleanup: true
  project: ./build/
  domain: react-scroll-parallax.surge.sh
  on: v2