language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
script: codecov && yarn storybook:export
deploy:
  skip_cleanup: true
  provider: surge
  project: build
  domain: react-scroll-parallax.surge.sh
  on: v2