language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
deploy:
  skip_cleanup: true
  provider: surge
  script: yarn run storybook:export
  project: build
  domain: react-scroll-parallax.surge.sh
  on: v2